# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyApp-Map' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyApp-Map
  pod 'AlertToast'
  pod 'SDWebImageSwiftUI'
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  pod 'Kingfisher'

  
  
  target 'MyApp-MapTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyApp-MapUITests' do
    # Pods for testing
  end

end
